name: TestPlugin
version: '1.0.0'
main: me.osarikas.testPlugin.TestPlugin
api-version: '1.21'
commands:
  god:
    description: God power
    usage: /<command>
    permission: testplugin.god
  feed:
    description: Накормить самого себя
    usage: /<command>
  setspawn:
    description: Установить точку спавна
    usage: /<command>
    permission: testplugin.setspawn
  spawn:
    description: Телепортироваться на точку спавна
    usage: /<command>
  setjoinmessage:
    description: Установить сообщение при заходе на сервер. Используйте %player% для получения никнейма игрока
    usage: /<command>
    permission: testplugin.setjoinmessage
permissions:
  testplugin.god:
    description: Позволяет использовать /god
  testplugin.setspawn:
    description: Позволяет использовать /setspawn
  testplugin.setjoinmessage:
    description: Позволяет использовать /setjoinmessage